apiVersion: v1
kind: Service
metadata:
  name: secretsanta-generator-app
  labels:
    app: secretsanta-generator-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30080  
  selector:
    app: secretsanta-generator-app
